# Generated by Django 4.0.3 on 2022-04-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sId', models.IntegerField()),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
