# Generated by Django 4.0.3 on 2022-04-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdclass', '0002_students_delete_album_delete_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='l_name',
            field=models.EmailField(max_length=100),
        ),
    ]
